### ISSUE TITLE
Rename and description change not working

### ISSUE THREAD

**Issue by Jaydakin** [ddeeddii/ezitems-web-testing#2]
For some reason the name and descriptions will not change when i try to use this to make a mod. The custom sprites work, but the name and description are still the normal ones.

**Comment by ddeeddii** [comment]
Hi, thanks for submitting.
I've verified that this isn't a problem with the mod generator itself - that seems to work just fine

There's not much I can do without some additional resources, so please
- Check if there are any errors in the in-game console, send them here if there are
- Attach the `main.lua` of the mod and send it here
- Send a list of the mods you are using in case there's any conflict

**Comment by Jaydakin** [comment]
Okay so I get this error from Repentance Plus: "repentanceplus/scripts/EID. lua:313: attempt to index a nil value (field 'player')"
And I can confirm that disabling Repentance Plus makes the rename work properly

**Comment by ddeeddii** [comment]
Not entirely sure what causes it but changing the way original description is read fixes the issue. Compatibility with Repentance Plus (and this bug) should be fixed in the next update
